import { randomUUID } from "node:crypto";
import { z } from "zod";
import { bearThesisSchema, bullThesisSchema, claimSchema, contradictionSchema, judgeOutputSchema, plannerOutputSchema, researchReportSchema, scoutOutputSchema, scoreEvidence, type Claim, type ResearchReport, type SourceRecord } from "./schemas";

export type ResearchProvider = { run(query: string): Promise<ResearchReport> };
export const NEBIUS_MODELS = { nano: "nvidia/nvidia-nemotron-3-nano-30b-a3b", super: "nvidia/nemotron-3-super-120b-a12b", ultra: "nvidia/Nemotron-3-Ultra-550b-a55b" } as const;
const timestamp = () => new Date().toISOString();
const source = (id: string, title: string, publisher: string, url: string, type: SourceRecord["type"], excerpt: string, reliability: number, publishedAt?: string): SourceRecord => ({ id, title, publisher, url, type, excerpt, reliability, publishedAt, retrievedAt: timestamp(), evidenceScore: 0 });

type Workflow = { planner: z.infer<typeof plannerOutputSchema>; scout: z.infer<typeof scoutOutputSchema>; bull: z.infer<typeof bullThesisSchema>; bear: z.infer<typeof bearThesisSchema>; claims: Claim[]; contradictions: z.infer<typeof contradictionSchema>[]; judge: z.infer<typeof judgeOutputSchema>; stageTelemetry: z.infer<typeof import("./schemas").stageTelemetrySchema>[] };
function buildReport(query: string, mode: "demo" | "live" | "fallback", sources: SourceRecord[], workflow: Workflow, simulated: boolean) {
  const claims = workflow.claims.map(claim => ({ ...claim, evidenceScore: scoreEvidence(sources, claim) }));
  const scoredSources = sources.map(item => ({ ...item, evidenceScore: Math.max(item.reliability, claims.some(claim => claim.supportingSourceIds.includes(item.id)) ? (item.type === "primary" ? .9 : item.type === "secondary" ? .65 : .35) : 0) }));
  const at = timestamp();
  const trace = [["PLANNING", "Question decomposed into typed subquestions."], ["SEARCHING", `${scoredSources.length} sources collected with retrieval timestamps.`], ["VERIFYING", "Source tiers, metadata, and claim lineage validated."], ["CHALLENGING", "Bull and Bear theses evaluated against shared artifacts."], ["CONTRADICTION FOUND", `${workflow.contradictions.length} contradiction checks recorded.`], ["RECHECKING", "Evidence scores and unresolved claims recalculated."], ["VERDICT READY", "Judge rationale exposes claim and source IDs."]].map(([stage, detail]) => ({ stage, detail, at }));
  return researchReportSchema.parse({ runId: mode + "_" + Date.now(), query, mode, createdAt: at, verdict: workflow.judge.verdict, verdictSummary: workflow.judge.summary, confidence: workflow.judge.confidence, ...workflow, claims, sources: scoredSources, majorContradictions: workflow.contradictions.map(item => item.description), whatWouldChangeConclusion: workflow.judge.conditions, metrics: { claims: claims.length, sources: scoredSources.length, primarySources: scoredSources.filter(item => item.type === "primary").length, contradictions: workflow.contradictions.length, unresolvedClaims: claims.filter(item => item.status === "unverified").length, latencyMs: workflow.stageTelemetry.reduce((sum, item) => sum + item.latencyMs, 0) }, comparison: { simulated, standard: { verdict: simulated ? "CONFIDENT BULLISH" : "SINGLE-PASS", claims: 1, primarySources: 0, contradictions: 0, unresolved: 1, lineage: false, adjudicated: false }, proofScout: { verdict: workflow.judge.verdict, claims: claims.length, primarySources: scoredSources.filter(item => item.type === "primary").length, contradictions: workflow.contradictions.length, unresolved: claims.filter(item => item.status === "unverified").length, lineage: true, adjudicated: true } }, trace });
}

function demoWorkflow(query: string) {
  const sources = [source("s1", "Project documentation", "Project team", "https://example.com/project/docs", "primary", "The project describes its stated product scope and roadmap.", .86), source("s2", "Market overview", "Research Desk", "https://example.com/research/overview", "secondary", "A third-party overview summarizes adoption and market positioning.", .68), source("s3", "Community discussion: catalysts", "Community Forum", "https://example.com/community/catalysts", "community", "Community participants cite a possible catalyst, without primary confirmation.", .34), source("s4", "Activity snapshot", "Public Ledger Explorer", "https://example.com/ledger/activity", "primary", "Observed activity is directionally positive but does not establish causation.", .79)];
  const traceId = `trace_${randomUUID()}`;
  const planner = plannerOutputSchema.parse({ traceId, question: query, subquestions: ["What is directly documented?", "What independent signals support the narrative?", "Which claims remain unproven or conflicting?"], stages: ["plan", "scout", "verify", "bull", "bear", "judge"] });
  const scout = scoutOutputSchema.parse({ traceId, query, sources });
  const claims: Claim[] = [
    claimSchema.parse({ id: "c1", text: "The core product is described in the project's public documentation.", status: "verified", confidence: .84, evidenceScore: 0, supportingSourceIds: ["s1"], contradictingSourceIds: [], rationale: "A primary project source directly describes the shipped scope." }),
    claimSchema.parse({ id: "c2", text: "Recent activity is directionally consistent with increased user interest.", status: "verified", confidence: .71, evidenceScore: 0, supportingSourceIds: ["s4", "s2"], contradictingSourceIds: [], rationale: "Activity and secondary analysis point in the same direction, with limited context." }),
    claimSchema.parse({ id: "c3", text: "A near-term catalyst is confirmed by a primary source.", status: "unverified", confidence: .28, evidenceScore: 0, supportingSourceIds: ["s3"], contradictingSourceIds: [], rationale: "The only mention is community-sourced and has no primary confirmation." }),
    claimSchema.parse({ id: "c4", text: "The current narrative is sufficient evidence of sustainable demand.", status: "contradicted", confidence: .76, evidenceScore: 0, supportingSourceIds: ["s2"], contradictingSourceIds: ["s4"], rationale: "Narrative strength exceeds what the available activity data can establish." })
  ];
  const bull = bullThesisSchema.parse({ position: "BULL", summary: "Primary documentation and directional activity support a credible product narrative.", claims: ["c1", "c2"], confidence: .66 });
  const bear = bearThesisSchema.parse({ position: "BEAR", summary: "The catalyst is unconfirmed and activity does not establish sustainable demand.", claims: ["c3", "c4"], confidence: .78 });
  const contradictions = [contradictionSchema.parse({ id: "x1", claimId: "c3", description: "Community catalyst claim lacks primary confirmation.", severity: "material", sourceIds: ["s1", "s3"] }), contradictionSchema.parse({ id: "x2", claimId: "c4", description: "Positive activity does not prove sustainable demand.", severity: "material", sourceIds: ["s2", "s4"] })];
  const judge = judgeOutputSchema.parse({ verdict: "MIXED", summary: "The bullish narrative has credible signals, but the evidence is incomplete and two material claims remain unverified or overstated.", confidence: .68, claimIds: claims.map(item => item.id), contradictionIds: contradictions.map(item => item.id), supportingClaimIds: ["c1", "c2"], contradictingClaimIds: ["c4"], unresolvedClaimIds: ["c3"], sourceIds: sources.map(item => item.id), conditions: ["A dated primary announcement confirming the catalyst.", "Several weeks of retention or repeat-usage data.", "Independent reconciliation of activity with circulating supply and liquidity."] });
  const stageTelemetry = ["planner", "scout", "verify", "bull", "bear", "contradictions", "judge"].map(stage => ({ stage, provider: "deterministic-demo", model: "demo-fixture", latencyMs: 0 }));
  return { sources, workflow: { planner, scout, bull, bear, claims, contradictions, judge, stageTelemetry } };
}

export function demoProvider(): ResearchProvider { return { async run(query) { const result = demoWorkflow(query); return buildReport(query, "demo", result.sources, result.workflow, true); } }; }

function classifySource(url: string): SourceRecord["type"] { const host = new URL(url).hostname.toLowerCase(); if (/(^|\.)nvidia\.com$|(^|\.)nebius\.com$|(^|\.)sec\.gov$|(^|\.)gov$|(^|\.)edu$/.test(host)) return "primary"; if (/(^|\.)reddit\.com$|(^|\.)x\.com$|(^|\.)twitter\.com$|(^|\.)discord\.com$|(^|\.)telegram\.org$/.test(host)) return "community"; return "secondary"; }
async function tavilySources(query: string): Promise<SourceRecord[]> { const key = process.env.TAVILY_API_KEY; if (!key) return []; const response = await fetch("https://api.tavily.com/search", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ api_key: key, query, max_results: 8, search_depth: "advanced", include_answer: false }), signal: AbortSignal.timeout(20000) }); if (!response.ok) throw new Error(`Tavily search failed (${response.status}).`); const data = await response.json() as { results?: Array<{ url: string; title: string; content?: string; published_date?: string }> }; return (data.results ?? []).filter(item => item.url && item.title).map((item, index) => source(`web_${index + 1}`, item.title, new URL(item.url).hostname, item.url, classifySource(item.url), item.content || "No excerpt supplied by Tavily.", .5, item.published_date)); }

function parseJson(content: string) { const cleaned = content.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim(); const start = cleaned.indexOf("{"); const end = cleaned.lastIndexOf("}"); if (start < 0 || end < start) throw new Error("Nebius returned no JSON object."); return JSON.parse(cleaned.slice(start, end + 1)); }
async function nebiusJson<T>(model: string, instruction: string, schema: z.ZodType<T>, name: string): Promise<T> { const key = process.env.NEBIUS_API_KEY; if (!key) throw new Error("NEBIUS_API_KEY is required for live mode."); const base = (process.env.NEBIUS_BASE_URL || "https://api.tokenfactory.us-central1.nebius.com/v1").replace(/\/$/, ""); let lastError = ""; for (let attempt = 0; attempt < 3; attempt++) { try { const response = await fetch(`${base}/chat/completions`, { method: "POST", headers: { Authorization: `Bearer ${key}`, "content-type": "application/json" }, body: JSON.stringify({ model, temperature: 0, response_format: { type: "json_object" }, messages: [{ role: "system", content: `Return only valid JSON matching ${name}. Do not use markdown.` }, { role: "user", content: instruction }] }), signal: AbortSignal.timeout(30000) }); if (!response.ok) throw new Error(`Nebius request failed (${response.status}).`); const data = await response.json() as { choices?: Array<{ message?: { content?: string } }> }; const content = data.choices?.[0]?.message?.content ?? ""; return schema.parse(parseJson(content)); } catch (error) { lastError = error instanceof Error ? error.message : "Unknown Nebius error."; if (attempt < 2) await new Promise(resolve => setTimeout(resolve, 350 * (attempt + 1))); } } throw new Error(`${name} failed after retries: ${lastError}`); }

async function liveWorkflow(query: string) { const traceId = `trace_${randomUUID()}`; const stageTelemetry: Workflow["stageTelemetry"] = []; const timed = async <T>(stage: string, model: string, operation: () => Promise<T>) => { const started = Date.now(); const value = await operation(); stageTelemetry.push({ stage, provider: "nebius-token-factory", model, latencyMs: Date.now() - started }); return value; }; const planner = await timed("planner", NEBIUS_MODELS.super, () => nebiusJson(NEBIUS_MODELS.super, `Question: ${query}; traceId: ${traceId}; create subquestions and stages.`, plannerOutputSchema, "PlannerOutput")); const webSources = await tavilySources(query); const scout = await timed("scout", NEBIUS_MODELS.nano, () => nebiusJson(NEBIUS_MODELS.nano, `Question: ${query}; planner: ${JSON.stringify(planner)}; candidate sources: ${JSON.stringify(webSources)}; normalize source records. Keep metadata present in candidates and never invent dates.`, scoutOutputSchema, "ScoutOutput")); const claimsRaw = await timed("verify", NEBIUS_MODELS.nano, () => nebiusJson(NEBIUS_MODELS.nano, `Question: ${query}; sources: ${JSON.stringify(scout.sources)}; produce claim mappings with IDs that refer only to these sources.`, z.object({ claims: z.array(claimSchema.omit({ evidenceScore: true })) }), "Claims")); const claims = claimsRaw.claims.map(claim => claimSchema.parse({ ...claim, evidenceScore: 0 })); const bull = await timed("bull", NEBIUS_MODELS.super, () => nebiusJson(NEBIUS_MODELS.super, `Question: ${query}; claims: ${JSON.stringify(claims)}; produce a BULL thesis.`, bullThesisSchema, "BullThesis")); const bear = await timed("bear", NEBIUS_MODELS.super, () => nebiusJson(NEBIUS_MODELS.super, `Question: ${query}; claims: ${JSON.stringify(claims)}; produce a BEAR thesis.`, bearThesisSchema, "BearThesis")); const contradictions = await timed("contradictions", NEBIUS_MODELS.super, () => nebiusJson(NEBIUS_MODELS.super, `Claims: ${JSON.stringify(claims)}; bull: ${JSON.stringify(bull)}; bear: ${JSON.stringify(bear)}; list source-backed contradictions only.`, z.object({ contradictions: z.array(contradictionSchema) }), "Contradictions")); const judge = await timed("judge", NEBIUS_MODELS.ultra, () => nebiusJson(NEBIUS_MODELS.ultra, `Question: ${query}; claims: ${JSON.stringify(claims)}; contradictions: ${JSON.stringify(contradictions.contradictions)}; return a conditional verdict with supportingClaimIds, contradictingClaimIds, unresolvedClaimIds, sourceIds, and conditions.`, judgeOutputSchema, "JudgeOutput")); return { sources: scout.sources, workflow: { planner, scout, bull, bear, claims, contradictions: contradictions.contradictions, judge, stageTelemetry } }; }
export function nebiusProvider(): ResearchProvider { return { async run(query) { const result = await liveWorkflow(query); return buildReport(query, "live", result.sources, result.workflow, false); } }; }
export function getResearchProvider(): ResearchProvider { return process.env.NEXT_PUBLIC_DEMO_MODE === "false" ? { async run(query) { try { return await nebiusProvider().run(query); } catch (error) { const result = demoWorkflow(query); const report = buildReport(query, "fallback", result.sources, result.workflow, true); return { ...report, verdictSummary: `Live provider unavailable; showing deterministic fallback. ${error instanceof Error ? error.message : "Unknown live error."}` }; } } } : demoProvider(); }
