import { randomUUID } from "node:crypto";
import { z } from "zod";
import { bearThesisSchema, bullThesisSchema, claimSchema, contradictionSchema, judgeOutputSchema, plannerOutputSchema, researchReportSchema, scoutOutputSchema, type Claim, type ResearchReport, type SourceRecord } from "./schemas";

export type ResearchProvider = { run(query: string): Promise<ResearchReport> };
export const NEBIUS_MODELS = { fast: "nvidia/nvidia-nemotron-3-nano-30b-a3b", planner: "nvidia/nemotron-3-super-120b-a12b", judge: "nvidia/Nemotron-3-Ultra-550b-a55b" } as const;
const source = (id: string, title: string, publisher: string, url: string, type: SourceRecord["type"], excerpt: string, reliability: number): SourceRecord => ({ id, title, publisher, url, type, excerpt, reliability });
const timestamp = () => new Date().toISOString();

function stages(query: string, traceId: string, sources: SourceRecord[]) {
  const planner = plannerOutputSchema.parse({ traceId, question: query, subquestions: ["What is directly documented?", "What independent signals support the narrative?", "Which claims remain unproven or conflicting?"], stages: ["plan", "scout", "verify", "bull", "bear", "judge"] });
  const scout = scoutOutputSchema.parse({ traceId, query, sources });
  const claims: Claim[] = [
    claimSchema.parse({ id: "c1", text: "The core product is described in the project's public documentation.", status: "verified", confidence: .84, supportingSourceIds: ["s1"], contradictingSourceIds: [], rationale: "A primary project source directly describes the shipped scope." }),
    claimSchema.parse({ id: "c2", text: "Recent activity is directionally consistent with increased user interest.", status: "verified", confidence: .71, supportingSourceIds: ["s4", "s2"], contradictingSourceIds: [], rationale: "Activity and secondary analysis point in the same direction, with limited context." }),
    claimSchema.parse({ id: "c3", text: "A near-term catalyst is confirmed by a primary source.", status: "unverified", confidence: .28, supportingSourceIds: ["s3"], contradictingSourceIds: [], rationale: "The only mention is community-sourced and has no primary confirmation." }),
    claimSchema.parse({ id: "c4", text: "The current narrative is sufficient evidence of sustainable demand.", status: "contradicted", confidence: .76, supportingSourceIds: ["s2"], contradictingSourceIds: ["s4"], rationale: "Narrative strength exceeds what the available activity data can establish." })
  ];
  const bull = bullThesisSchema.parse({ position: "BULL", summary: "Primary documentation and directional activity support a credible product narrative.", claims: ["c1", "c2"], confidence: .66 });
  const bear = bearThesisSchema.parse({ position: "BEAR", summary: "The catalyst is unconfirmed and activity does not establish sustainable demand.", claims: ["c3", "c4"], confidence: .78 });
  const contradictions = [contradictionSchema.parse({ id: "x1", claimId: "c3", description: "Community catalyst claim lacks primary confirmation.", severity: "material", sourceIds: ["s1", "s3"] }), contradictionSchema.parse({ id: "x2", claimId: "c4", description: "Positive activity does not prove sustainable demand.", severity: "material", sourceIds: ["s2", "s4"] })];
  const judge = judgeOutputSchema.parse({ verdict: "MIXED", summary: "The bullish narrative has credible signals, but the evidence is incomplete and two material claims remain unverified or overstated.", confidence: .68, claimIds: claims.map(c => c.id), contradictionIds: contradictions.map(c => c.id), conditions: ["A dated primary announcement confirming the catalyst.", "Several weeks of retention or repeat-usage data.", "Independent reconciliation of activity with circulating supply and liquidity."] });
  return { planner, scout, bull, bear, claims, contradictions, judge };
}

export function demoProvider(): ResearchProvider { return { async run(query) {
  const sources = [source("s1", "Project documentation", "Project team", "https://example.com/project/docs", "primary", "The project describes its stated product scope and roadmap.", .86), source("s2", "Market overview", "Research Desk", "https://example.com/research/overview", "secondary", "A third-party overview summarizes adoption and market positioning.", .68), source("s3", "Community discussion: catalysts", "Community Forum", "https://example.com/community/catalysts", "community", "Community participants cite a possible catalyst, without primary confirmation.", .34), source("s4", "Activity snapshot", "Public Ledger Explorer", "https://example.com/ledger/activity", "primary", "Observed activity is directionally positive but does not establish causation.", .79)];
  const traceId = `trace_${randomUUID()}`; const workflow = stages(query, traceId, sources); const at = timestamp();
  const trace = [["PLANNING", "Split the question into product, activity, catalyst, and demand claims."], ["SEARCHING", "Collected primary, secondary, and community evidence."], ["VERIFYING", "Validated source quality and mapped claims to source IDs."], ["CHALLENGING", "Bull and Bear theses were evaluated against the same artifacts."], ["CONTRADICTION FOUND", "Found a gap between narrative and proof of sustainable demand."], ["RECHECKING", "Re-ranked claims after contradiction review."], ["VERDICT READY", "Evidence is mixed; conviction should remain conditional."]].map(([stage, detail]) => ({ stage, detail, at }));
  return researchReportSchema.parse({ runId: `demo_${Date.now()}`, query, mode: "demo", createdAt: at, verdict: workflow.judge.verdict, verdictSummary: workflow.judge.summary, confidence: workflow.judge.confidence, ...workflow, sources, majorContradictions: workflow.contradictions.map(c => c.description), whatWouldChangeConclusion: workflow.judge.conditions, comparison: { simulated: true, standard: { verdict: "CONFIDENT BULLISH", claims: 1, contradictions: 0, sources: 0 }, proofScout: { verdict: workflow.judge.verdict, claims: workflow.claims.length, contradictions: workflow.contradictions.length, sources: sources.length } }, trace });
}}; }

async function tavilySources(query: string): Promise<SourceRecord[]> { const key = process.env.TAVILY_API_KEY; if (!key) return []; const response = await fetch("https://api.tavily.com/search", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ api_key: key, query, max_results: 5, search_depth: "advanced" }) }); if (!response.ok) throw new Error(`Tavily search failed (${response.status}).`); const data = await response.json() as { results?: Array<{ url: string; title: string; content?: string }> }; return (data.results ?? []).map((item, i) => source(`web_${i + 1}`, item.title, new URL(item.url).hostname, item.url, "secondary", item.content ?? "Search result excerpt.", .5)); }
async function nebiusJson<T>(model: string, instruction: string, name: string): Promise<T> { const key = process.env.NEBIUS_API_KEY; if (!key) throw new Error("NEBIUS_API_KEY is required for live mode."); const base = (process.env.NEBIUS_BASE_URL || "https://api.tokenfactory.nebius.com/v1").replace(/\/$/, ""); const response = await fetch(`${base}/chat/completions`, { method: "POST", headers: { Authorization: `Bearer ${key}`, "content-type": "application/json" }, body: JSON.stringify({ model, temperature: 0, messages: [{ role: "system", content: `Return only valid JSON matching ${name}.` }, { role: "user", content: instruction }] }) }); if (!response.ok) throw new Error(`Nebius request failed (${response.status}).`); const data = await response.json() as { choices?: Array<{ message?: { content?: string } }> }; const content = data.choices?.[0]?.message?.content ?? ""; const json = content.match(/\{[\s\S]*\}/)?.[0]; if (!json) throw new Error(`Nebius returned invalid ${name} JSON.`); return JSON.parse(json) as T; }
export function nebiusProvider(): ResearchProvider { return { async run(query) {
  const traceId = `trace_${randomUUID()}`; const planner = plannerOutputSchema.parse(await nebiusJson(NEBIUS_MODELS.planner, `Question: ${query}; traceId: ${traceId}; create subquestions and stages.`, "PlannerOutput")); const webSources = await tavilySources(query); const scout = scoutOutputSchema.parse(await nebiusJson(NEBIUS_MODELS.fast, `Question: ${query}; planner: ${JSON.stringify(planner)}; candidate sources: ${JSON.stringify(webSources)}; normalize source records.`, "ScoutOutput")); const claims = z.array(claimSchema).parse(await nebiusJson(NEBIUS_MODELS.fast, `Question: ${query}; sources: ${JSON.stringify(scout.sources)}; produce claim mappings.`, "Claim[]")); const bull = bullThesisSchema.parse(await nebiusJson(NEBIUS_MODELS.planner, `Question: ${query}; claims: ${JSON.stringify(claims)}; produce a BULL thesis.`, "BullThesis")); const bear = bearThesisSchema.parse(await nebiusJson(NEBIUS_MODELS.planner, `Question: ${query}; claims: ${JSON.stringify(claims)}; produce a BEAR thesis.`, "BearThesis")); const contradictions = z.array(contradictionSchema).parse(await nebiusJson(NEBIUS_MODELS.planner, `Claims: ${JSON.stringify(claims)}; bull: ${JSON.stringify(bull)}; bear: ${JSON.stringify(bear)}; list contradictions.`, "Contradiction[]")); const judge = judgeOutputSchema.parse(await nebiusJson(NEBIUS_MODELS.judge, `Question: ${query}; claims: ${JSON.stringify(claims)}; contradictions: ${JSON.stringify(contradictions)}; return a conditional verdict.`, "JudgeOutput"));
  const at = timestamp(); const trace = [["PLANNING", "PlannerOutput validated."], ["SEARCHING", "ScoutOutput validated with optional Tavily results."], ["VERIFYING", "Claims validated against source IDs."], ["CHALLENGING", "Bull and Bear theses validated."], ["CONTRADICTION FOUND", "Contradiction artifacts validated."], ["RECHECKING", "Judge reconciled typed artifacts."], ["VERDICT READY", "FinalReport validated."]].map(([stage, detail]) => ({ stage, detail, at })); return researchReportSchema.parse({ runId: `live_${Date.now()}`, query, mode: "live", createdAt: at, verdict: judge.verdict, verdictSummary: judge.summary, confidence: judge.confidence, planner, scout, bull, bear, claims, sources: scout.sources, contradictions, majorContradictions: contradictions.map(c => c.description), whatWouldChangeConclusion: judge.conditions, judge, comparison: { simulated: true, standard: { verdict: "UNAVAILABLE", claims: 0, contradictions: 0, sources: 0 }, proofScout: { verdict: judge.verdict, claims: claims.length, contradictions: contradictions.length, sources: scout.sources.length } }, trace });
}}; }
export function getResearchProvider(): ResearchProvider { return process.env.NEXT_PUBLIC_DEMO_MODE === "false" ? nebiusProvider() : demoProvider(); }
